In [48]:
# https://numpy.org/devdocs/user/quickstart.html
import numpy as np

In [2]:
it = [3, 6, 7, 11]
type(it) #list has all datatypes. int,string all

list

In [4]:
n = np.array(it)
type(n) #numpy array is like same in c++
#n.size

numpy.ndarray

In [16]:
twod = np.array([[1, 2, 5], [3, 4,5]])
twod  #make same shape otherwise type will be object list
#twod.size

array([[1, 2, 5],
       [3, 4, 5]])

In [10]:
y = np.array([2, 5, 6, "77"])
y  #converts all into unicode
#type(y)

array(['2', '5', '6', '77'], dtype='<U11')

In [14]:
n.shape #row n col

(4,)

In [17]:
twod.shape

(2, 3)

In [18]:
twod.size #multipy shaoe

6

In [19]:
list(range(9, 16)) #print from 9 to n-1

[9, 10, 11, 12, 13, 14, 15]

In [20]:
list(range(9, 16, 2)) #print by skipping 2

[9, 11, 13, 15]

In [22]:
np.arange(7) #arange is numpy implentation of range as in lists

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
np.arange(7,12,2)

array([ 7,  9, 11])

In [25]:
#arange is same as this
np.array(range(7,12,2))

array([ 7,  9, 11])

In [39]:
#question mark trick
np.arange?
#can do for any function


Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

In [35]:
np.arange(40).reshape(8,5) #to reshape row n col

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [42]:
arr1 = np.arange(40)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [43]:
arr2 = arr1.reshape(8,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [44]:
arr1[0] = 1000 #changes arr2 also

In [45]:
arr1

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39])

In [46]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [47]:
arr1 is arr2

False